name: qcsymsim

channels:
  - conda-forge

dependencies:
  - python
  - sympy
  - numpy
  - matplotlib
  - tqdm
  - openqasm3
  - qiskit
  - qiskit-ibm-runtime
  - qiskit-aer
  - ipykernel
  - pylatexenc
  - pytest
  - pytest-cov