include("src.jl")
import LinearAlgebra
#target_state = [0.5+0im, 0.5+0im, 0.5+0im, 0.5+0im]
target_state = Array{ComplexF64}(collect(1:16))
#target_state = Array{ComplexF64}([1, 2*im, 3, 4*im, 5, 6*im, 7, 8*im])
target_state += ComplexF64.(1.0im*collect((size(target_state,1)-1):-1:0))
target_state = target_state ./ LinearAlgebra.norm(target_state, 2)
display(target_state)
sp = MottonenStatePreparation.StatePreparator(target_state)
MottonenStatePreparation.compute_y_angles(sp)
display(sp.alphas_y)
MottonenStatePreparation.compute_z_angles(sp)
display(sp.alphas_z)
MottonenStatePreparation.compute_theta_y_angles(sp)
display(sp.theta_y_angles)
MottonenStatePreparation.compute_theta_z_angles(sp)
display(sp.theta_z_angles)
MottonenStatePreparation.compute_control_qubits(sp)
display(sp.control_qubits)

println()
println()

sp2 = MottonenStatePreparation.StatePreparator(target_state, true)
display(sp2.alphas_y)
display(sp2.alphas_z)
display(sp2.theta_y_angles)
display(sp2.theta_z_angles)
display(sp2.control_qubits)